apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxs
spec:
  replicas: 20
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-multi
        image: ruo91/nginx:latest
        ports:
        - containerPort: 80
