apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxs
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-single
        image: ruo91/nginx:latest
        ports:
        - containerPort: 80
